// Английские строки. Ключ — русский текст из кода; недостающий ключ выводится как есть.
nonisolated let englishStrings: [String: String] = [
    "Протестировать импульс": "Test pulse",
    "Язык": "Language",
    "Every Noise — работает": "Every Noise — running",
    "Every Noise — остановлено": "Every Noise — stopped",
    "Every Noise — ошибка": "Every Noise — error",
    "Встроенные динамики": "Built-in speakers",
    "Разъём 3,5 мм": "3.5 mm jack",
    "Составное устройство": "Aggregate device",
    "Устройство вывода": "Output device",
    "Неизвестное подключение": "Unknown connection",
    "Внешнее устройство": "External device",
    "источник вывода": "output source",
    "частота дискретизации": "sample rate",
    "мьют": "mute",
    "громкость": "volume",
    "устройство вывода": "output device",
    "Не найдено активное устройство вывода звука": "No active audio output device found",
    "Аудиодвижок не запустился: %@": "Audio engine failed to start: %@",
    "Не удалось подготовить буфер тона": "Could not prepare the tone buffer",
    "Информация": "Info",
    "Предупреждение": "Warning",
    "Ошибка": "Error",
    "Запись журнала включена": "Logging enabled",
    "Запись журнала выключена": "Logging disabled",
    "Журнал очищен": "Log cleared",
    "Ротация журнала: предыдущий файл сохранён как %@": "Log rotated: previous file saved as %@",
    "%@ (сборка %@)": "%@ (build %@)",
    "Тег: %@": "Tag: %@",
    "Коммит: %@": "Commit: %@",
    "Собрано: %@": "Built: %@",
    "Архитектуры: %@": "Architectures: %@",
    "Every Noise уже запущен (PID %d) — активирую его и выхожу": "Every Noise is already running (PID %d) — activating it and quitting",
    "Автозапуск не настроен: %@": "Could not set up launch at login: %@",
    "Every Noise запущен (%@)": "Every Noise started (%@)",
    "Автостарт выключен — ожидание команды пользователя": "Auto-start is off — waiting for the user",
    "перед выходом из приложения": "before quitting",
    "Every Noise завершает работу": "Every Noise is shutting down",
    "За маком никого — пауза, чтобы он мог уснуть. Вернётесь — импульсы продолжатся": "Nobody at the Mac — paused so it can sleep. Pulses resume when you come back",
    "Mac спит — импульсы остановлены, продолжатся после пробуждения": "The Mac is asleep — pulses stopped, they resume after wake",
    "Пауза: Mac простаивает": "Paused: Mac is idle",
    "Пауза: Mac спит": "Paused: Mac is asleep",
    "после возвращения к Mac": "when you return to the Mac",
    "после пробуждения Mac": "after the Mac wakes",
    "Остановлено": "Stopped",
    "Работает": "Running",
    "аудиотракт пересобран": "audio chain rebuilt",
    "Текущий вывод: %@, %d Гц": "Current output: %@, %d Hz",
    "Не удалось запустить аудиодвижок: %@": "Could not start the audio engine: %@",
    "Запуск: %@, импульс %@, %@, уровень %@": "Started: %@, %@ pulse, %@, level %@",
    "по команде пользователя": "by user command",
    "Остановлено %@": "Stopped %@",
    "Импульс": "Pulse",
    "Импульс вручную": "Manual pulse",
    "%@ №%d: %@, %@, уровень %@": "%@ #%d: %@, %@, level %@",
    ", вывод %@ @ %d Гц": ", output %@ @ %d Hz",
    "неизвестно": "unknown",
    ", удержание маршрута включено": ", route hold on",
    "Частота %@ недоступна на %d Гц и снижена до %@. Поднимите частоту дискретизации в «Настройке Audio-MIDI» или включите подстройку частоты.": "%@ is not available at %d Hz and was lowered to %@. Raise the sample rate in Audio MIDI Setup or turn on frequency adaptation.",
    "Вывод %@ замьючен или громкость на нуле — усилитель сигнал не увидит.": "Output %@ is muted or at zero volume — the amplifier will not see the signal.",
    "Системная громкость %d %%: на аналоговом выходе сигнал может не дотянуть до порога детектора усилителя.": "System volume is %d %% — on an analog output the signal may not reach the amplifier's detection threshold.",
    "Импульс не воспроизведён: %@": "Pulse was not played: %@",
    "Пауза по простою выключена — импульсы возобновлены": "Idle pause turned off — pulses resumed",
    "Пауза: за маком %d минут никого — аудиотракт отпущен, чтобы Mac мог уснуть": "Paused: nobody at the Mac for %d minutes — audio released so the Mac can sleep",
    "Пользователь вернулся — импульсы возобновлены": "User is back — pulses resumed",
    "Аудиодвижок не стартовал: %@": "Audio engine did not start: %@",
    "Удержание маршрута включено: непрерывная несущая %@ на −70 dBFS (%@)": "Route hold on: continuous %@ carrier at −70 dBFS (%@)",
    "маршрут": "route",
    "Не удалось включить удержание маршрута: %@": "Could not enable route hold: %@",
    "Удержание маршрута выключено": "Route hold off",
    "%@: частота снижена с %@ до %@. Выбор в настройках не изменён.": "%@: frequency lowered from %@ to %@. Your setting is unchanged.",
    "Возврат к выбранной частоте %@": "Back to the selected frequency %@",
    "Маршрут": "Route",
    "%@ сжимает звук кодеком AAC и режет всё выше ~18 кГц": "%@ compresses audio with AAC and cuts everything above ~18 kHz",
    "%@ работает на %d Гц": "%@ runs at %d Hz",
    "%@ сжимает звук кодеком AAC и срезает всё выше ~18 кГц: тон %@ до усилителя, скорее всего, не дойдёт. Выберите 17–18 кГц или включите подстройку частоты.": "%@ compresses audio with AAC and cuts everything above ~18 kHz: a %@ tone will most likely not reach the amplifier. Pick 17–18 kHz or turn on frequency adaptation.",
    "AirPlay работает на 44,1 кГц и добавляет задержку около 2 секунд — импульс короче 1 секунды может не дойти целиком.": "AirPlay runs at 44.1 kHz and adds about 2 seconds of latency — a pulse shorter than 1 second may not get through in full.",
    "Маршрут изменился (%@): %@, %d Гц": "Route changed (%@): %@, %d Hz",
    "Маршрут изменился (%@): активного устройства вывода нет": "Route changed (%@): no active output device",
    "Настройки изменены: %@, %@, импульс %@, уровень %@": "Settings changed: %@, %@, %@ pulse, level %@",
    "Mac уходит в сон": "The Mac is going to sleep",
    "Mac уходит в сон — импульсы остановлены, аудиотракт отпущен": "The Mac is going to sleep — pulses stopped, audio released",
    "Mac проснулся": "The Mac woke up",
    "Mac проснулся, но за ним никого — импульсы остаются на паузе": "The Mac woke up but nobody is there — pulses stay paused",
    "Mac проснулся — импульсы возобновлены": "The Mac woke up — pulses resumed",
    "Периодическое воспроизведение неслышимого тона": "Periodic playback of an inaudible tone",
    "%.1f кГц": "%.1f kHz",
    "%.0f Гц": "%.0f Hz",
    "15 с": "15 s",
    "30 с": "30 s",
    "1 мин": "1 min",
    "2 мин": "2 min",
    "3 мин": "3 min",
    "5 мин": "5 min",
    "10 мин": "10 min",
    "15 мин": "15 min",
    "30 мин": "30 min",
    "1 час": "1 hour",
    "Каждые 15 секунд": "Every 15 seconds",
    "Каждые 30 секунд": "Every 30 seconds",
    "Каждую минуту": "Every minute",
    "Каждые 2 минуты": "Every 2 minutes",
    "Каждые 3 минуты": "Every 3 minutes",
    "Каждые 5 минут": "Every 5 minutes",
    "Каждые 10 минут": "Every 10 minutes",
    "Каждые 15 минут": "Every 15 minutes",
    "Каждые 30 минут": "Every 30 minutes",
    "Каждый час": "Every hour",
    "10 Гц · инфразвук, часто срезается": "10 Hz · infrasound, often filtered out",
    "20 Гц · нижняя граница слуха": "20 Hz · lower limit of hearing",
    "17 кГц · слышат подростки": "17 kHz · teenagers can hear it",
    "18 кГц · для AirPlay и Bluetooth": "18 kHz · for AirPlay and Bluetooth",
    "19 кГц · запасной вариант": "19 kHz · fallback",
    "20 кГц · рекомендуется": "20 kHz · recommended",
    "22 кГц · нужен выход ≥ 48 кГц": "22 kHz · needs output ≥ 48 kHz",
    "10 Гц": "10 Hz",
    "20 Гц": "20 Hz",
    "17 кГц": "17 kHz",
    "18 кГц": "18 kHz",
    "19 кГц": "19 kHz",
    "20 кГц": "20 kHz",
    "22 кГц": "22 kHz",
    "Ниже порога слышимости человека. Не все тракты его пропускают: разделительные конденсаторы и фильтры ВЧ-среза в усилителе часто режут всё ниже 20 Гц, и детектор сигнала тона не увидит.": "Below the threshold of human hearing. Not every chain passes it: coupling capacitors and subsonic filters in the amplifier often cut everything below 20 Hz, and the signal detector never sees the tone.",
    "Формально на границе слышимости: тон не различим как звук, но крупные напольные колонки могут отдавать лёгким гулом и заметным ходом диффузора.": "Technically at the edge of hearing: the tone is not perceived as sound, but large floorstanders may produce a faint rumble and visible cone movement.",
    "Не слышат почти все люди старше 25 лет, но подростки, дети и домашние животные слышат хорошо. Берите, только если верхние пресеты не будят усилитель.": "Inaudible to almost everyone over 25, but teenagers, children and pets hear it well. Use it only if the higher presets fail to wake the amplifier.",
    "Неслышимо для подавляющего большинства взрослых. Компромисс, если 19–20 кГц теряются в тракте.": "Inaudible to the vast majority of adults. A compromise when 19–20 kHz gets lost in the chain.",
    "Неслышимо практически для всех. Основной запасной вариант, если на 20 кГц усилитель не просыпается.": "Inaudible to virtually everyone. The main fallback when the amplifier does not wake at 20 kHz.",
    "Верхняя граница слышимости человека, реально не слышит никто. Проходит через тракт 44,1 кГц и выше — универсальный выбор по умолчанию.": "The upper limit of human hearing — nobody actually hears it. Passes through 44.1 kHz chains and above, the universal default.",
    "Гарантированно неслышимо, но требует выхода 48 кГц и выше: на 44,1 кГц частота упирается в Найквиста и будет подавлена фильтром ЦАП.": "Guaranteed inaudible, but needs a 48 kHz output or higher: at 44.1 kHz it runs into Nyquist and gets suppressed by the DAC filter.",
    "0,25 с": "0.25 s",
    "0,5 с": "0.5 s",
    "1 с": "1 s",
    "2 с": "2 s",
    "3 с": "3 s",
    "Автоматически": "Automatic",
    "Всегда": "Always",
    "Никогда": "Never",
    "Записей нет": "No entries",
    "События появятся, как только приложение начнёт воспроизводить импульсы.": "Events will appear as soon as the app starts playing pulses.",
    "Запись журнала выключена.": "Logging is turned off.",
    "Запись выключена — новые события не сохраняются": "Logging is off — new events are not saved",
    "Запись": "Logging",
    "Записывать события в журнал и в файл": "Record events in the log and the file",
    "Уровень": "Level",
    "Все": "All",
    "Показать в Finder": "Show in Finder",
    "Очистить": "Clear",
    "Статус": "Status",
    "Настройки": "Settings",
    "Журнал": "Log",
    "Приостановить": "Pause",
    "Запустить": "Start",
    "Воспроизвести сейчас": "Play now",
    "Частота": "Frequency",
    "Периодичность": "Interval",
    "Открыть Every Noise": "Open Every Noise",
    "Выйти": "Quit",
    "Ошибка: %@": "Error: %@",
    "Длительность импульса": "Pulse length",
    "Расписание": "Schedule",
    "Большинство усилителей засыпает через 10–20 минут тишины. Импульс раз в 30 секунд — с запасом; длиннее 1 секунды нужно, если детектор сигнала усилителя срабатывает медленно.": "Most amplifiers fall asleep after 10–20 minutes of silence, so a pulse every 30 seconds has plenty of margin. Go longer than 1 second if the amplifier's signal detector is slow.",
    "Тон": "Tone",
    "тихо": "quiet",
    "громко": "loud",
    "Уровень сигнала": "Signal level",
    "Детектору усилителя обычно хватает нескольких милливольт. Начните с 10–15 %: этого достаточно, чтобы разбудить технику, и мало, чтобы нагружать твитеры. Поднимайте, если усилитель всё равно засыпает.": "A few millivolts are usually enough for the amplifier's detector. Start at 10–15 %: enough to wake the gear, little enough to spare the tweeters. Raise it if the amplifier still falls asleep.",
    "Удержание маршрута": "Route hold",
    "Подстраивать частоту под подключение": "Adapt frequency to the connection",
    "Подключение усилителя": "Amplifier connection",
    "AirPlay и Bluetooth разрывают сессию на тишине: усилитель успевает заснуть между импульсами, а начало следующего импульса съедается переподключением. В режиме удержания приложение непрерывно отдаёт ту же частоту на −70 dBFS — это на 40 дБ ниже порога слышимости и не нагружает твитеры, но маршрут остаётся живым. «Автоматически» включает удержание только для AirPlay, Bluetooth и составных устройств; для джека 3,5 мм и USB оно не нужно.\n\nПодстройка частоты нужна там же: кодек AAC режет всё выше ~18 кГц, поэтому на AirPlay и Bluetooth приложение играет 18 кГц вместо выбранных 19–22. Выбор в пикере «Частота» при этом не меняется — как только вернётесь на джек или USB, заиграет он.": "AirPlay and Bluetooth tear the session down on silence: the amplifier falls asleep between pulses and reconnection eats the start of the next one. With route hold the app continuously emits the same frequency at −70 dBFS — 40 dB below the hearing threshold, harmless to tweeters, but the route stays alive. \u{201C}Automatic\u{201D} enables it only for AirPlay, Bluetooth and aggregate devices; a 3.5 mm jack or USB does not need it.\n\nFrequency adaptation matters in the same places: the AAC codec cuts everything above ~18 kHz, so on AirPlay and Bluetooth the app plays 18 kHz instead of the selected 19–22. Your choice in the Frequency picker stays as it is — switch back to jack or USB and it plays again.",
    "Приостанавливать при простое Mac": "Pause when the Mac is idle",
    "Запускать импульсы при старте приложения": "Start pulses when the app launches",
    "Запускать Every Noise при входе в систему": "Launch Every Noise at login",
    "Приложение": "Application",
    "Пока приложение играет, macOS считает, что идёт звук, и не даёт Mac уснуть по бездействию. Поэтому после 5 минут без действий пользователя импульсы останавливаются, а аудиотракт отпускается — Mac засыпает как обычно. При первом же движении мыши импульсы возобновляются. Выключайте, только если Mac и так не должен спать.\n\nАвтозапуск работает только для приложения, лежащего в /Applications.": "While the app is playing, macOS treats it as active audio and will not let the Mac sleep on idle. So after 5 minutes without user input the pulses stop and the audio chain is released — the Mac sleeps as usual. The first mouse move resumes them. Turn this off only if the Mac is not supposed to sleep anyway.\n\nLaunch at login works only for an app living in /Applications.",
    "Версия": "Version",
    "Тег": "Tag",
    "Коммит": "Commit",
    "Собрано": "Built",
    "Архитектуры": "Architectures",
    "Скопировано": "Copied",
    "Скопировать для отчёта": "Copy for a report",
    "Сборка": "Build",
    "Сигнал": "Signal",
    "Вывод": "Output",
    "Устройство": "Device",
    "не определено": "not detected",
    "Подключение": "Connection",
    "Частота дискретизации": "Sample rate",
    "включено": "on",
    "выключено": "off",
    "Громкость системы": "System volume",
    "Последний импульс": "Last pulse",
    "Следующий импульс": "Next pulse",
    "Импульсов с запуска": "Pulses this session",
    "Вывод «%@» замьючен или громкость на нуле — усилитель не увидит сигнал.": "Output \u{201C}%@\u{201D} is muted or at zero volume — the amplifier will not see the signal.",
    "Тон снижен до %d Гц: устройство работает на %d Гц. Поднимите частоту дискретизации в «Настройке Audio-MIDI» или выберите пресет ниже.": "The tone was lowered to %d Hz: the device runs at %d Hz. Raise the sample rate in Audio MIDI Setup or pick a lower preset.",
    "Для %@ нужна частота дискретизации не ниже %d Гц, а устройство работает на %d Гц.": "%@ needs a sample rate of at least %d Hz, but the device runs at %d Hz.",
    "%@ · подстроено под %@": "%@ · adapted for %@",
    "не регулируется устройством": "not controlled by the device",
    "ещё не было": "none yet",
    "%@ · %d с назад": "%@ · %d s ago",
    "сейчас": "now",
    "через %d с": "in %d s",
    "Остановить": "Stop",
    "Усилитель получает неслышимый тон по расписанию": "The amplifier receives an inaudible tone on schedule",
    "Импульсы не воспроизводятся, усилитель может уснуть": "No pulses are playing, the amplifier may fall asleep",
]
